import { createPost,getPostByUserId,deletePost, getAllPosts, updatePost, likePost,toggleSavePost } from "../controllers/post.controller";
import express from "express";
import { protect } from "../middleware/authmiddleware";
import upload from "../middleware/multer";
const router=express.Router();
router.post("/createPost", protect,upload.array("media",5),createPost);
router.get("/getAllPosts", protect, getAllPosts);
router.get("/getPostByUserId",protect,getPostByUserId);
router.delete("/deletePost/:id",protect,deletePost);
router.put("/updatePost/:id",protect,upload.array("media",5),updatePost);
router.post("/likePost/:id",protect,likePost);
router.post("/toggleSavePost/:id",protect,toggleSavePost);
export default router;